kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv5
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv5"